version: '3.8'

services:
  base-datos:
    image: postgres:15-alpine
    container_name: bd-evaluacion-devops
    environment:
      POSTGRES_USER: user_devops
      POSTGRES_PASSWORD: password_seguro123
      POSTGRES_DB: devops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devops-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_devops -d devops_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  api-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend-devops
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://base-datos:5432/devops_db
      - SPRING_DATASOURCE_USERNAME=user_devops
      - SPRING_DATASOURCE_PASSWORD=password_seguro123
    depends_on:
      base-datos:
        condition: service_healthy
    networks:
      - devops-network
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 256M

volumes:
  postgres_data:

networks:
  devops-network:
    driver: bridge