name: Integracion Continua y Seguridad

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  construir-y-probar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y ejecutar pruebas
        run: mvn clean verify -f demo/pom.xml

  revision-sonarcloud:
    needs: construir-y-probar
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Análisis de código en SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -f demo/pom.xml verify sonar:sonar \
            -Dsonar.projectKey=thomys229_evaluacion-devops \
            -Dsonar.organization=thomys229 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN}

  revision-snyk:
    needs: construir-y-probar
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar y ejecutar Snyk
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          chmod +x demo/mvnw
          npm install -g snyk
          snyk test --severity-threshold=high --file=demo/pom.xml


  deploy:
    needs: [construir-y-probar, revision-sonarcloud, revision-snyk]
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Levantar entorno con Docker Compose
        run: docker compose up -d --build

      - name: Verificar estado de los contenedores
        run: |
          sleep 15
          docker ps